<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Advisee;

class AdviseeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        $data = [
                [
                'id' => ' 1 ',
                'user_id' => ' 1 ',
                'student_id' => ' 1 ',
                'term_id' => ' 1 ',
               ],
               [
                'id' => ' 2 ',
                'user_id' => ' 1 ',
                'student_id' => ' 1 ',
                'term_id' => ' 2 ',
               ],
               [
                'id' => ' 3 ',
                'user_id' => ' 1 ',
                'student_id' => ' 1 ',
                'term_id' => ' 3 ',
               ],
               [
                'id' => ' 4 ',
                'user_id' => ' 1 ',
                'student_id' => ' 1 ',
                'term_id' => ' 4 ',
               ],
               [
                'id' => ' 5 ',
                'user_id' => ' 1 ',
                'student_id' => ' 2 ',
                'term_id' => ' 1 ',
               ],
               [
                'id' => ' 6 ',
                'user_id' => ' 1 ',
                'student_id' => ' 2 ',
                'term_id' => ' 2 ',
               ],
               [
                'id' => ' 7 ',
                'user_id' => ' 1 ',
                'student_id' => ' 2 ',
                'term_id' => ' 3 ',
               ],
               [
                'id' => ' 8 ',
                'user_id' => ' 1 ',
                'student_id' => ' 2 ',
                'term_id' => ' 4 ',
               ],
               [
                'id' => ' 9 ',
                'user_id' => ' 1 ',
                'student_id' => ' 3 ',
                'term_id' => ' 1 ',
               ],
               [
                'id' => ' 10 ',
                'user_id' => ' 1 ',
                'student_id' => ' 3 ',
                'term_id' => ' 2 ',
               ],
               [
                'id' => ' 11 ',
                'user_id' => ' 1 ',
                'student_id' => ' 3 ',
                'term_id' => ' 3 ',
               ],
               [
                'id' => ' 12 ',
                'user_id' => ' 1 ',
                'student_id' => ' 3 ',
                'term_id' => ' 4 ',
               ],
               [
                'id' => ' 13 ',
                'user_id' => ' 1 ',
                'student_id' => ' 4 ',
                'term_id' => ' 1 ',
               ],
               [
                'id' => ' 14 ',
                'user_id' => ' 1 ',
                'student_id' => ' 4 ',
                'term_id' => ' 2 ',
               ],
               [
                'id' => ' 15 ',
                'user_id' => ' 1 ',
                'student_id' => ' 4 ',
                'term_id' => ' 3 ',
               ],
               [
                'id' => ' 16 ',
                'user_id' => ' 1 ',
                'student_id' => ' 4 ',
                'term_id' => ' 4 ',
               ],
               [
                'id' => ' 17 ',
                'user_id' => ' 1 ',
                'student_id' => ' 5 ',
                'term_id' => ' 1 ',
               ],
               [
                'id' => ' 18 ',
                'user_id' => ' 1 ',
                'student_id' => ' 5 ',
                'term_id' => ' 2 ',
               ],
               [
                'id' => ' 19 ',
                'user_id' => ' 1 ',
                'student_id' => ' 5 ',
                'term_id' => ' 3 ',
               ],
               [
                'id' => ' 20 ',
                'user_id' => ' 1 ',
                'student_id' => ' 5 ',
                'term_id' => ' 4 ',
               ],
               [
                'id' => ' 21 ',
                'user_id' => ' 1 ',
                'student_id' => ' 6 ',
                'term_id' => ' 1 ',
               ],
               [
                'id' => ' 22 ',
                'user_id' => ' 1 ',
                'student_id' => ' 6 ',
                'term_id' => ' 2 ',
               ],
               [
                'id' => ' 23 ',
                'user_id' => ' 1 ',
                'student_id' => ' 6 ',
                'term_id' => ' 3 ',
               ],
               [
                'id' => ' 24 ',
                'user_id' => ' 1 ',
                'student_id' => ' 6 ',
                'term_id' => ' 4 ',
               ],
               [
                'id' => ' 25 ',
                'user_id' => ' 1 ',
                'student_id' => ' 7 ',
                'term_id' => ' 1 ',
               ],
               [
                'id' => ' 26 ',
                'user_id' => ' 1 ',
                'student_id' => ' 7 ',
                'term_id' => ' 2 ',
               ],
               [
                'id' => ' 27 ',
                'user_id' => ' 1 ',
                'student_id' => ' 7 ',
                'term_id' => ' 3 ',
               ],
               [
                'id' => ' 28 ',
                'user_id' => ' 1 ',
                'student_id' => ' 7 ',
                'term_id' => ' 4 ',
               ],
               [
                'id' => ' 29 ',
                'user_id' => ' 1 ',
                'student_id' => ' 8 ',
                'term_id' => ' 1 ',
               ],
               [
                'id' => ' 30 ',
                'user_id' => ' 1 ',
                'student_id' => ' 8 ',
                'term_id' => ' 2 ',
               ],
               [
                'id' => ' 31 ',
                'user_id' => ' 1 ',
                'student_id' => ' 8 ',
                'term_id' => ' 3 ',
               ],
               [
                'id' => ' 32 ',
                'user_id' => ' 1 ',
                'student_id' => ' 8 ',
                'term_id' => ' 4 ',
               ],
               [
                'id' => ' 33 ',
                'user_id' => ' 1 ',
                'student_id' => ' 9 ',
                'term_id' => ' 1 ',
               ],
               [
                'id' => ' 34 ',
                'user_id' => ' 1 ',
                'student_id' => ' 9 ',
                'term_id' => ' 2 ',
               ],
               [
                'id' => ' 35 ',
                'user_id' => ' 1 ',
                'student_id' => ' 9 ',
                'term_id' => ' 3 ',
               ],
               [
                'id' => ' 36 ',
                'user_id' => ' 1 ',
                'student_id' => ' 9 ',
                'term_id' => ' 4 ',
               ],
               [
                'id' => ' 37 ',
                'user_id' => ' 1 ',
                'student_id' => ' 10 ',
                'term_id' => ' 1 ',
               ],
               [
                'id' => ' 38 ',
                'user_id' => ' 1 ',
                'student_id' => ' 10 ',
                'term_id' => ' 2 ',
               ],
               [
                'id' => ' 39 ',
                'user_id' => ' 1 ',
                'student_id' => ' 10 ',
                'term_id' => ' 3 ',
               ],
               [
                'id' => ' 40 ',
                'user_id' => ' 1 ',
                'student_id' => ' 10 ',
                'term_id' => ' 4 ',
               ],

               [
                'id' => ' 41 ',
                'user_id' => ' 2 ',
                'student_id' => ' 11 ',
                'term_id' => ' 1 ',
               ],
               [
                'id' => ' 42 ',
                'user_id' => ' 2 ',
                'student_id' => ' 11 ',
                'term_id' => ' 2 ',
               ],
               [
                'id' => ' 43 ',
                'user_id' => ' 2 ',
                'student_id' => ' 11 ',
                'term_id' => ' 3 ',
               ],
               [
                'id' => ' 44 ',
                'user_id' => ' 2 ',
                'student_id' => ' 11 ',
                'term_id' => ' 4 ',
               ],
               [
                'id' => ' 45 ',
                'user_id' => ' 2 ',
                'student_id' => ' 12 ',
                'term_id' => ' 1 ',
               ],
               [
                'id' => ' 46 ',
                'user_id' => ' 2 ',
                'student_id' => ' 12 ',
                'term_id' => ' 2 ',
               ],
               [
                'id' => ' 47 ',
                'user_id' => ' 2 ',
                'student_id' => ' 12 ',
                'term_id' => ' 3 ',
               ],
               [
                'id' => ' 48 ',
                'user_id' => ' 2 ',
                'student_id' => ' 12 ',
                'term_id' => ' 4 ',
               ],
               [
                'id' => ' 49 ',
                'user_id' => ' 2 ',
                'student_id' => ' 13 ',
                'term_id' => ' 1 ',
               ],
               [
                'id' => ' 50 ',
                'user_id' => ' 2 ',
                'student_id' => ' 13 ',
                'term_id' => ' 2 ',
               ],
               [
                'id' => ' 51 ',
                'user_id' => ' 2 ',
                'student_id' => ' 13 ',
                'term_id' => ' 3 ',
               ],
               [
                'id' => ' 52 ',
                'user_id' => ' 2 ',
                'student_id' => ' 13 ',
                'term_id' => ' 4 ',
               ],
               [
                'id' => ' 53 ',
                'user_id' => ' 2 ',
                'student_id' => ' 14 ',
                'term_id' => ' 1 ',
               ],
               [
                'id' => ' 54 ',
                'user_id' => ' 2 ',
                'student_id' => ' 14 ',
                'term_id' => ' 2 ',
               ],
               [
                'id' => ' 55 ',
                'user_id' => ' 2 ',
                'student_id' => ' 14 ',
                'term_id' => ' 3 ',
               ],
               [
                'id' => ' 56 ',
                'user_id' => ' 2 ',
                'student_id' => ' 14 ',
                'term_id' => ' 4 ',
               ],
               [
                'id' => ' 57 ',
                'user_id' => ' 2 ',
                'student_id' => ' 15 ',
                'term_id' => ' 1 ',
               ],
               [
                'id' => ' 58 ',
                'user_id' => ' 2 ',
                'student_id' => ' 15 ',
                'term_id' => ' 2 ',
               ],
               [
                'id' => ' 59 ',
                'user_id' => ' 2 ',
                'student_id' => ' 15 ',
                'term_id' => ' 3 ',
               ],
               [
                'id' => ' 60 ',
                'user_id' => ' 2 ',
                'student_id' => ' 15 ',
                'term_id' => ' 4 ',
               ],
               [
                'id' => ' 61 ',
                'user_id' => ' 2 ',
                'student_id' => ' 16 ',
                'term_id' => ' 1 ',
               ],
               [
                'id' => ' 62 ',
                'user_id' => ' 2 ',
                'student_id' => ' 16 ',
                'term_id' => ' 2 ',
               ],
               [
                'id' => ' 63 ',
                'user_id' => ' 2 ',
                'student_id' => ' 16 ',
                'term_id' => ' 3 ',
               ],
               [
                'id' => ' 64 ',
                'user_id' => ' 2 ',
                'student_id' => ' 16 ',
                'term_id' => ' 4 ',
               ],
               [
                'id' => ' 65 ',
                'user_id' => ' 2 ',
                'student_id' => ' 17 ',
                'term_id' => ' 1 ',
               ],
               [
                'id' => ' 66 ',
                'user_id' => ' 2 ',
                'student_id' => ' 17 ',
                'term_id' => ' 2 ',
               ],
               [
                'id' => ' 67 ',
                'user_id' => ' 2 ',
                'student_id' => ' 17 ',
                'term_id' => ' 3 ',
               ],
               [
                'id' => ' 68 ',
                'user_id' => ' 2 ',
                'student_id' => ' 17 ',
                'term_id' => ' 4 ',
               ],
               [
                'id' => ' 69 ',
                'user_id' => ' 2 ',
                'student_id' => ' 18 ',
                'term_id' => ' 1 ',
               ],
               [
                'id' => ' 70 ',
                'user_id' => ' 2 ',
                'student_id' => ' 18 ',
                'term_id' => ' 2 ',
               ],
               [
                'id' => ' 71 ',
                'user_id' => ' 2 ',
                'student_id' => ' 18 ',
                'term_id' => ' 3 ',
               ],
               [
                'id' => ' 72 ',
                'user_id' => ' 2 ',
                'student_id' => ' 18 ',
                'term_id' => ' 4 ',
               ],
               [
                'id' => ' 73 ',
                'user_id' => ' 2 ',
                'student_id' => ' 19 ',
                'term_id' => ' 1 ',
               ],
               [
                'id' => ' 74 ',
                'user_id' => ' 2 ',
                'student_id' => ' 19 ',
                'term_id' => ' 2 ',
               ],
               [
                'id' => ' 75 ',
                'user_id' => ' 2 ',
                'student_id' => ' 19 ',
                'term_id' => ' 3 ',
               ],
               [
                'id' => ' 76 ',
                'user_id' => ' 2 ',
                'student_id' => ' 19 ',
                'term_id' => ' 4 ',
               ],
               [
                'id' => ' 77 ',
                'user_id' => ' 2 ',
                'student_id' => ' 20 ',
                'term_id' => ' 1 ',
               ],
               [
                'id' => ' 78 ',
                'user_id' => ' 2 ',
                'student_id' => ' 20 ',
                'term_id' => ' 2 ',
               ],
               [
                'id' => ' 79 ',
                'user_id' => ' 2 ',
                'student_id' => ' 20 ',
                'term_id' => ' 3 ',
               ],
               [
                'id' => ' 80 ',
                'user_id' => ' 2 ',
                'student_id' => ' 20 ',
                'term_id' => ' 4 ',
               ],

               [
                'id' => ' 81 ',
                'user_id' => ' 3 ',
                'student_id' => ' 21 ',
                'term_id' => ' 1 ',
               ],
               [
                'id' => ' 82 ',
                'user_id' => ' 3 ',
                'student_id' => ' 21 ',
                'term_id' => ' 2 ',
               ],
               [
                'id' => ' 83 ',
                'user_id' => ' 3 ',
                'student_id' => ' 21 ',
                'term_id' => ' 3 ',
               ],
               [
                'id' => ' 84 ',
                'user_id' => ' 3 ',
                'student_id' => ' 21 ',
                'term_id' => ' 4 ',
               ],
               [
                'id' => ' 85 ',
                'user_id' => ' 3 ',
                'student_id' => ' 22 ',
                'term_id' => ' 1 ',
               ],
               [
                'id' => ' 86 ',
                'user_id' => ' 3 ',
                'student_id' => ' 22 ',
                'term_id' => ' 2 ',
               ],
               [
                'id' => ' 87 ',
                'user_id' => ' 3 ',
                'student_id' => ' 22 ',
                'term_id' => ' 3 ',
               ],
               [
                'id' => ' 88 ',
                'user_id' => ' 3 ',
                'student_id' => ' 22 ',
                'term_id' => ' 4 ',
               ],
               [
                'id' => ' 89 ',
                'user_id' => ' 3 ',
                'student_id' => ' 23 ',
                'term_id' => ' 1 ',
               ],
               [
                'id' => ' 90 ',
                'user_id' => ' 3 ',
                'student_id' => ' 23 ',
                'term_id' => ' 2 ',
               ],
               [
                'id' => ' 91 ',
                'user_id' => ' 3 ',
                'student_id' => ' 23 ',
                'term_id' => ' 3 ',
               ],
               [
                'id' => ' 92 ',
                'user_id' => ' 3 ',
                'student_id' => ' 23 ',
                'term_id' => ' 4 ',
               ],
               [
                'id' => ' 93 ',
                'user_id' => ' 3 ',
                'student_id' => ' 24 ',
                'term_id' => ' 1 ',
               ],
               [
                'id' => ' 94 ',
                'user_id' => ' 3 ',
                'student_id' => ' 24 ',
                'term_id' => ' 2 ',
               ],
               [
                'id' => ' 95 ',
                'user_id' => ' 3 ',
                'student_id' => ' 24 ',
                'term_id' => ' 3 ',
               ],
               [
                'id' => ' 96 ',
                'user_id' => ' 3 ',
                'student_id' => ' 24 ',
                'term_id' => ' 4 ',
               ],
               [
                'id' => ' 97 ',
                'user_id' => ' 3 ',
                'student_id' => ' 25 ',
                'term_id' => ' 1 ',
               ],
               [
                'id' => ' 98 ',
                'user_id' => ' 3 ',
                'student_id' => ' 25 ',
                'term_id' => ' 2 ',
               ],
               [
                'id' => ' 99 ',
                'user_id' => ' 3 ',
                'student_id' => ' 25 ',
                'term_id' => ' 3 ',
               ],
               [
                'id' => ' 100 ',
                'user_id' => ' 3 ',
                'student_id' => ' 25 ',
                'term_id' => ' 4 ',
               ],
               [
                'id' => ' 101 ',
                'user_id' => ' 3 ',
                'student_id' => ' 26 ',
                'term_id' => ' 1 ',
               ],
               [
                'id' => ' 102 ',
                'user_id' => ' 3 ',
                'student_id' => ' 26 ',
                'term_id' => ' 2 ',
               ],
               [
                'id' => ' 103 ',
                'user_id' => ' 3 ',
                'student_id' => ' 26 ',
                'term_id' => ' 3 ',
               ],
               [
                'id' => ' 104 ',
                'user_id' => ' 3 ',
                'student_id' => ' 26 ',
                'term_id' => ' 4 ',
               ],
               [
                'id' => ' 105 ',
                'user_id' => ' 3 ',
                'student_id' => ' 27 ',
                'term_id' => ' 1 ',
               ],
               [
                'id' => ' 106 ',
                'user_id' => ' 3 ',
                'student_id' => ' 27 ',
                'term_id' => ' 2 ',
               ],
               [
                'id' => ' 107 ',
                'user_id' => ' 3 ',
                'student_id' => ' 27 ',
                'term_id' => ' 3 ',
               ],
               [
                'id' => ' 108 ',
                'user_id' => ' 3 ',
                'student_id' => ' 27 ',
                'term_id' => ' 4 ',
               ],
               [
                'id' => ' 109 ',
                'user_id' => ' 3 ',
                'student_id' => ' 28 ',
                'term_id' => ' 1 ',
               ],
               [
                'id' => ' 110 ',
                'user_id' => ' 3 ',
                'student_id' => ' 28 ',
                'term_id' => ' 2 ',
               ],
               [
                'id' => ' 111 ',
                'user_id' => ' 3 ',
                'student_id' => ' 28 ',
                'term_id' => ' 3 ',
               ],
               [
                'id' => ' 112 ',
                'user_id' => ' 3 ',
                'student_id' => ' 28 ',
                'term_id' => ' 4 ',
               ],
               [
                'id' => ' 113 ',
                'user_id' => ' 3 ',
                'student_id' => ' 29 ',
                'term_id' => ' 1 ',
               ],
               [
                'id' => ' 114 ',
                'user_id' => ' 3 ',
                'student_id' => ' 29 ',
                'term_id' => ' 2 ',
               ],
               [
                'id' => ' 115 ',
                'user_id' => ' 3 ',
                'student_id' => ' 29 ',
                'term_id' => ' 3 ',
               ],
               [
                'id' => ' 116 ',
                'user_id' => ' 3 ',
                'student_id' => ' 29 ',
                'term_id' => ' 4 ',
               ],
               [
                'id' => ' 117 ',
                'user_id' => ' 3 ',
                'student_id' => ' 30 ',
                'term_id' => ' 1 ',
               ],
               [
                'id' => ' 118 ',
                'user_id' => ' 3 ',
                'student_id' => ' 30 ',
                'term_id' => ' 2 ',
               ],
               [
                'id' => ' 119 ',
                'user_id' => ' 3 ',
                'student_id' => ' 30 ',
                'term_id' => ' 3 ',
               ],
               [
                'id' => ' 120 ',
                'user_id' => ' 3 ',
                'student_id' => ' 30 ',
                'term_id' => ' 4 ',
               ],

               [
                'id' => ' 121 ',
                'user_id' => ' 4 ',
                'student_id' => ' 31 ',
                'term_id' => ' 1 ',
               ],
               [
                'id' => ' 122 ',
                'user_id' => ' 4 ',
                'student_id' => ' 31 ',
                'term_id' => ' 2 ',
               ],
               [
                'id' => ' 123 ',
                'user_id' => ' 4 ',
                'student_id' => ' 31 ',
                'term_id' => ' 3 ',
               ],
               [
                'id' => ' 124 ',
                'user_id' => ' 4 ',
                'student_id' => ' 31 ',
                'term_id' => ' 4 ',
               ],
               [
                'id' => ' 125 ',
                'user_id' => ' 4 ',
                'student_id' => ' 32 ',
                'term_id' => ' 1 ',
               ],
               [
                'id' => ' 126 ',
                'user_id' => ' 4 ',
                'student_id' => ' 32 ',
                'term_id' => ' 2 ',
               ],
               [
                'id' => ' 127 ',
                'user_id' => ' 4 ',
                'student_id' => ' 32 ',
                'term_id' => ' 3 ',
               ],
               [
                'id' => ' 128 ',
                'user_id' => ' 4 ',
                'student_id' => ' 32 ',
                'term_id' => ' 4 ',
               ],
               [
                'id' => ' 129 ',
                'user_id' => ' 4 ',
                'student_id' => ' 33 ',
                'term_id' => ' 1 ',
               ],
               [
                'id' => ' 130 ',
                'user_id' => ' 4 ',
                'student_id' => ' 33 ',
                'term_id' => ' 2 ',
               ],
               [
                'id' => ' 131 ',
                'user_id' => ' 4 ',
                'student_id' => ' 33 ',
                'term_id' => ' 3 ',
               ],
               [
                'id' => ' 132 ',
                'user_id' => ' 4 ',
                'student_id' => ' 33 ',
                'term_id' => ' 4 ',
               ],
               [
                'id' => ' 133 ',
                'user_id' => ' 4 ',
                'student_id' => ' 34 ',
                'term_id' => ' 1 ',
               ],
               [
                'id' => ' 134 ',
                'user_id' => ' 4 ',
                'student_id' => ' 34 ',
                'term_id' => ' 2 ',
               ],
               [
                'id' => ' 135 ',
                'user_id' => ' 4 ',
                'student_id' => ' 34 ',
                'term_id' => ' 3 ',
               ],
               [
                'id' => ' 136 ',
                'user_id' => ' 4 ',
                'student_id' => ' 34 ',
                'term_id' => ' 4 ',
               ],
               [
                'id' => ' 137 ',
                'user_id' => ' 4 ',
                'student_id' => ' 35 ',
                'term_id' => ' 1 ',
               ],
               [
                'id' => ' 138 ',
                'user_id' => ' 4 ',
                'student_id' => ' 35 ',
                'term_id' => ' 2 ',
               ],
               [
                'id' => ' 139 ',
                'user_id' => ' 4 ',
                'student_id' => ' 35 ',
                'term_id' => ' 3 ',
               ],
               [
                'id' => ' 140 ',
                'user_id' => ' 4 ',
                'student_id' => ' 35 ',
                'term_id' => ' 4 ',
               ],
               [
                'id' => ' 141 ',
                'user_id' => ' 4 ',
                'student_id' => ' 36 ',
                'term_id' => ' 1 ',
               ],
               [
                'id' => ' 142 ',
                'user_id' => ' 4 ',
                'student_id' => ' 36 ',
                'term_id' => ' 2 ',
               ],
               [
                'id' => ' 143 ',
                'user_id' => ' 4 ',
                'student_id' => ' 36 ',
                'term_id' => ' 3 ',
               ],
               [
                'id' => ' 144 ',
                'user_id' => ' 4 ',
                'student_id' => ' 36 ',
                'term_id' => ' 4 ',
               ],
               [
                'id' => ' 145 ',
                'user_id' => ' 4 ',
                'student_id' => ' 37 ',
                'term_id' => ' 1 ',
               ],
               [
                'id' => ' 146 ',
                'user_id' => ' 4 ',
                'student_id' => ' 37 ',
                'term_id' => ' 2 ',
               ],
               [
                'id' => ' 147 ',
                'user_id' => ' 4 ',
                'student_id' => ' 37 ',
                'term_id' => ' 3 ',
               ],
               [
                'id' => ' 148 ',
                'user_id' => ' 4 ',
                'student_id' => ' 37 ',
                'term_id' => ' 4 ',
               ],
               [
                'id' => ' 149 ',
                'user_id' => ' 4 ',
                'student_id' => ' 38 ',
                'term_id' => ' 1 ',
               ],
               [
                'id' => ' 150 ',
                'user_id' => ' 4 ',
                'student_id' => ' 38 ',
                'term_id' => ' 2 ',
               ],
               [
                'id' => ' 151 ',
                'user_id' => ' 4 ',
                'student_id' => ' 38 ',
                'term_id' => ' 3 ',
               ],
               [
                'id' => ' 152 ',
                'user_id' => ' 4 ',
                'student_id' => ' 38 ',
                'term_id' => ' 4 ',
               ],
               [
                'id' => ' 153 ',
                'user_id' => ' 4 ',
                'student_id' => ' 39 ',
                'term_id' => ' 1 ',
               ],
               [
                'id' => ' 154 ',
                'user_id' => ' 4 ',
                'student_id' => ' 39 ',
                'term_id' => ' 2 ',
               ],
               [
                'id' => ' 155 ',
                'user_id' => ' 4 ',
                'student_id' => ' 39 ',
                'term_id' => ' 3 ',
               ],
               [
                'id' => ' 156 ',
                'user_id' => ' 4 ',
                'student_id' => ' 39 ',
                'term_id' => ' 4 ',
               ],
               [
                'id' => ' 157 ',
                'user_id' => ' 4 ',
                'student_id' => ' 40 ',
                'term_id' => ' 1 ',
               ],
               [
                'id' => ' 158 ',
                'user_id' => ' 4 ',
                'student_id' => ' 40 ',
                'term_id' => ' 2 ',
               ],
               [
                'id' => ' 159 ',
                'user_id' => ' 4 ',
                'student_id' => ' 40 ',
                'term_id' => ' 3 ',
               ],
               [
                'id' => ' 160 ',
                'user_id' => ' 4 ',
                'student_id' => ' 40 ',
                'term_id' => ' 4 ',
               ],

               [
                'id' => ' 161 ',
                'user_id' => ' 5 ',
                'student_id' => ' 41 ',
                'term_id' => ' 1 ',
               ],
               [
                'id' => ' 162 ',
                'user_id' => ' 5 ',
                'student_id' => ' 41 ',
                'term_id' => ' 2 ',
               ],
               [
                'id' => ' 163 ',
                'user_id' => ' 5 ',
                'student_id' => ' 41 ',
                'term_id' => ' 3 ',
               ],
               [
                'id' => ' 164 ',
                'user_id' => ' 5 ',
                'student_id' => ' 41 ',
                'term_id' => ' 4 ',
               ],
               [
                'id' => ' 165 ',
                'user_id' => ' 5 ',
                'student_id' => ' 42 ',
                'term_id' => ' 1 ',
               ],
               [
                'id' => ' 166 ',
                'user_id' => ' 5 ',
                'student_id' => ' 42 ',
                'term_id' => ' 2 ',
               ],
               [
                'id' => ' 167 ',
                'user_id' => ' 5 ',
                'student_id' => ' 42 ',
                'term_id' => ' 3 ',
               ],
               [
                'id' => ' 168 ',
                'user_id' => ' 5 ',
                'student_id' => ' 42 ',
                'term_id' => ' 4 ',
               ],
               [
                'id' => ' 169 ',
                'user_id' => ' 5 ',
                'student_id' => ' 43 ',
                'term_id' => ' 1 ',
               ],
               [
                'id' => ' 170 ',
                'user_id' => ' 5 ',
                'student_id' => ' 43 ',
                'term_id' => ' 2 ',
               ],
               [
                'id' => ' 171 ',
                'user_id' => ' 5 ',
                'student_id' => ' 43 ',
                'term_id' => ' 3 ',
               ],
               [
                'id' => ' 172 ',
                'user_id' => ' 5 ',
                'student_id' => ' 43 ',
                'term_id' => ' 4 ',
               ],
               [
                'id' => ' 173 ',
                'user_id' => ' 5 ',
                'student_id' => ' 44 ',
                'term_id' => ' 1 ',
               ],
               [
                'id' => ' 174 ',
                'user_id' => ' 5 ',
                'student_id' => ' 44 ',
                'term_id' => ' 2 ',
               ],
               [
                'id' => ' 175 ',
                'user_id' => ' 5 ',
                'student_id' => ' 44 ',
                'term_id' => ' 3 ',
               ],
               [
                'id' => ' 176 ',
                'user_id' => ' 5 ',
                'student_id' => ' 44 ',
                'term_id' => ' 4 ',
               ],
               [
                'id' => ' 177 ',
                'user_id' => ' 5 ',
                'student_id' => ' 45 ',
                'term_id' => ' 1 ',
               ],
               [
                'id' => ' 178 ',
                'user_id' => ' 5 ',
                'student_id' => ' 45 ',
                'term_id' => ' 2 ',
               ],
               [
                'id' => ' 179 ',
                'user_id' => ' 5 ',
                'student_id' => ' 45 ',
                'term_id' => ' 3 ',
               ],
               [
                'id' => ' 180 ',
                'user_id' => ' 5 ',
                'student_id' => ' 45 ',
                'term_id' => ' 4 ',
               ],
               [
                'id' => ' 181 ',
                'user_id' => ' 5 ',
                'student_id' => ' 46 ',
                'term_id' => ' 1 ',
               ],
               [
                'id' => ' 182 ',
                'user_id' => ' 5 ',
                'student_id' => ' 46 ',
                'term_id' => ' 2 ',
               ],
               [
                'id' => ' 183 ',
                'user_id' => ' 5 ',
                'student_id' => ' 46 ',
                'term_id' => ' 3 ',
               ],
               [
                'id' => ' 184 ',
                'user_id' => ' 5 ',
                'student_id' => ' 46 ',
                'term_id' => ' 4 ',
               ],
               [
                'id' => ' 185 ',
                'user_id' => ' 5 ',
                'student_id' => ' 47 ',
                'term_id' => ' 1 ',
               ],
               [
                'id' => ' 186 ',
                'user_id' => ' 5 ',
                'student_id' => ' 47 ',
                'term_id' => ' 2 ',
               ],
               [
                'id' => ' 187 ',
                'user_id' => ' 5 ',
                'student_id' => ' 47 ',
                'term_id' => ' 3 ',
               ],
               [
                'id' => ' 188 ',
                'user_id' => ' 5 ',
                'student_id' => ' 47 ',
                'term_id' => ' 4 ',
               ],
               [
                'id' => ' 189 ',
                'user_id' => ' 5 ',
                'student_id' => ' 48 ',
                'term_id' => ' 1 ',
               ],
               [
                'id' => ' 190 ',
                'user_id' => ' 5 ',
                'student_id' => ' 48 ',
                'term_id' => ' 2 ',
               ],
               [
                'id' => ' 191 ',
                'user_id' => ' 5 ',
                'student_id' => ' 48 ',
                'term_id' => ' 3 ',
               ],
               [
                'id' => ' 192 ',
                'user_id' => ' 5 ',
                'student_id' => ' 48 ',
                'term_id' => ' 4 ',
               ],
               [
                'id' => ' 193 ',
                'user_id' => ' 5 ',
                'student_id' => ' 49 ',
                'term_id' => ' 1 ',
               ],
               [
                'id' => ' 194 ',
                'user_id' => ' 5 ',
                'student_id' => ' 49 ',
                'term_id' => ' 2 ',
               ],
               [
                'id' => ' 195 ',
                'user_id' => ' 5 ',
                'student_id' => ' 49 ',
                'term_id' => ' 3 ',
               ],
               [
                'id' => ' 196 ',
                'user_id' => ' 5 ',
                'student_id' => ' 49 ',
                'term_id' => ' 4 ',
               ],
               [
                'id' => ' 197 ',
                'user_id' => ' 5 ',
                'student_id' => ' 50 ',
                'term_id' => ' 1 ',
               ],
               [
                'id' => ' 198 ',
                'user_id' => ' 5 ',
                'student_id' => ' 50 ',
                'term_id' => ' 2 ',
               ],
               [
                'id' => ' 199 ',
                'user_id' => ' 5 ',
                'student_id' => ' 50 ',
                'term_id' => ' 3 ',
               ],
               [
                'id' => ' 200 ',
                'user_id' => ' 5 ',
                'student_id' => ' 50 ',
                'term_id' => ' 4 ',
               ],
               [
                'id' => ' 201 ',
                'user_id' => ' 6 ',
                'student_id' => ' 61 ',
                'term_id' => ' 1 ',
               ],
               [
                'id' => ' 202 ',
                'user_id' => ' 6 ',
                'student_id' => ' 61 ',
                'term_id' => ' 2 ',
               ],
               [
                'id' => ' 203 ',
                'user_id' => ' 6 ',
                'student_id' => ' 61 ',
                'term_id' => ' 3 ',
               ],
               [
                'id' => ' 204 ',
                'user_id' => ' 6 ',
                'student_id' => ' 61 ',
                'term_id' => ' 4 ',
               ],
               [
                'id' => ' 205 ',
                'user_id' => ' 6 ',
                'student_id' => ' 62 ',
                'term_id' => ' 1 ',
               ],
               [
                'id' => ' 206 ',
                'user_id' => ' 6 ',
                'student_id' => ' 62 ',
                'term_id' => ' 2 ',
               ],
               [
                'id' => ' 207 ',
                'user_id' => ' 6 ',
                'student_id' => ' 62 ',
                'term_id' => ' 3 ',
               ],
               [
                'id' => ' 208 ',
                'user_id' => ' 6 ',
                'student_id' => ' 62 ',
                'term_id' => ' 4 ',
               ],
               [
                'id' => ' 209 ',
                'user_id' => ' 6 ',
                'student_id' => ' 63 ',
                'term_id' => ' 1 ',
               ],
               [
                'id' => ' 210 ',
                'user_id' => ' 6 ',
                'student_id' => ' 63 ',
                'term_id' => ' 2 ',
               ],
               [
                'id' => ' 211 ',
                'user_id' => ' 6 ',
                'student_id' => ' 63 ',
                'term_id' => ' 3 ',
               ],
               [
                'id' => ' 212 ',
                'user_id' => ' 6 ',
                'student_id' => ' 63 ',
                'term_id' => ' 4 ',
               ],
               [
                'id' => ' 213 ',
                'user_id' => ' 6 ',
                'student_id' => ' 64 ',
                'term_id' => ' 1 ',
               ],
               [
                'id' => ' 214 ',
                'user_id' => ' 6 ',
                'student_id' => ' 64 ',
                'term_id' => ' 2 ',
               ],
               [
                'id' => ' 215 ',
                'user_id' => ' 6 ',
                'student_id' => ' 64 ',
                'term_id' => ' 3 ',
               ],
               [
                'id' => ' 216 ',
                'user_id' => ' 6 ',
                'student_id' => ' 64 ',
                'term_id' => ' 4 ',
               ],
               [
                'id' => ' 217 ',
                'user_id' => ' 6 ',
                'student_id' => ' 65 ',
                'term_id' => ' 1 ',
               ],
               [
                'id' => ' 218 ',
                'user_id' => ' 6 ',
                'student_id' => ' 65 ',
                'term_id' => ' 2 ',
               ],
               [
                'id' => ' 219 ',
                'user_id' => ' 6 ',
                'student_id' => ' 65 ',
                'term_id' => ' 3 ',
               ],
               [
                'id' => ' 220 ',
                'user_id' => ' 6 ',
                'student_id' => ' 65 ',
                'term_id' => ' 4 ',
               ],
               [
                'id' => ' 221 ',
                'user_id' => ' 6 ',
                'student_id' => ' 66 ',
                'term_id' => ' 1 ',
               ],
               [
                'id' => ' 222 ',
                'user_id' => ' 6 ',
                'student_id' => ' 66 ',
                'term_id' => ' 2 ',
               ],
               [
                'id' => ' 223 ',
                'user_id' => ' 6 ',
                'student_id' => ' 66 ',
                'term_id' => ' 3 ',
               ],
               [
                'id' => ' 224 ',
                'user_id' => ' 6 ',
                'student_id' => ' 66 ',
                'term_id' => ' 4 ',
               ],
               [
                'id' => ' 225 ',
                'user_id' => ' 6 ',
                'student_id' => ' 67 ',
                'term_id' => ' 1 ',
               ],
               [
                'id' => ' 226 ',
                'user_id' => ' 6 ',
                'student_id' => ' 67 ',
                'term_id' => ' 2 ',
               ],
               [
                'id' => ' 227 ',
                'user_id' => ' 6 ',
                'student_id' => ' 67 ',
                'term_id' => ' 3 ',
               ],
               [
                'id' => ' 228 ',
                'user_id' => ' 6 ',
                'student_id' => ' 67 ',
                'term_id' => ' 4 ',
               ],
               [
                'id' => ' 229 ',
                'user_id' => ' 6 ',
                'student_id' => ' 68 ',
                'term_id' => ' 1 ',
               ],
               [
                'id' => ' 230 ',
                'user_id' => ' 6 ',
                'student_id' => ' 68 ',
                'term_id' => ' 2 ',
               ],
               [
                'id' => ' 231 ',
                'user_id' => ' 6 ',
                'student_id' => ' 68 ',
                'term_id' => ' 3 ',
               ],
               [
                'id' => ' 232 ',
                'user_id' => ' 6 ',
                'student_id' => ' 68 ',
                'term_id' => ' 4 ',
               ],
               [
                'id' => ' 233 ',
                'user_id' => ' 6 ',
                'student_id' => ' 69 ',
                'term_id' => ' 1 ',
               ],
               [
                'id' => ' 234 ',
                'user_id' => ' 6 ',
                'student_id' => ' 69 ',
                'term_id' => ' 2 ',
               ],
               [
                'id' => ' 235 ',
                'user_id' => ' 6 ',
                'student_id' => ' 69 ',
                'term_id' => ' 3 ',
               ],
               [
                'id' => ' 236 ',
                'user_id' => ' 6 ',
                'student_id' => ' 69 ',
                'term_id' => ' 4 ',
               ],
               [
                'id' => ' 237 ',
                'user_id' => ' 6 ',
                'student_id' => ' 70 ',
                'term_id' => ' 1 ',
               ],
               [
                'id' => ' 238 ',
                'user_id' => ' 6 ',
                'student_id' => ' 70 ',
                'term_id' => ' 2 ',
               ],
               [
                'id' => ' 239 ',
                'user_id' => ' 6 ',
                'student_id' => ' 70 ',
                'term_id' => ' 3 ',
               ],
               [
                'id' => ' 240 ',
                'user_id' => ' 6 ',
                'student_id' => ' 70 ',
                'term_id' => ' 4 ',
               ],
            
            ];
        Advisee::insert($data);
    }
}
